# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


language: r

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" R_KNITR_OPTIONS="knitr.chunk.tidy=TRUE" PATH=$HOME/bin:$PATH
    - secure: "u2Fg8f3eFdwaNIxBpo2joU1BB8Qb528WBUCFxLUBuYAXHyAmIalvcF6ArFHC4hmMRx39Dl2wnW7SV9hcLxiGLeym8OPkTQD4RiF4V7DORX19MQM+0yucI7tZ6g7tJ2hrBZj/R4qX75Hf2TVygp7+tChKe9F8e9NnKB81av06aWpbPXMDN/SczeQEIos34A3U2Q1p/NPC9FRYajn940EfGb2Hs8Ob6G5+qRUkyKQodbsnk6EMjMg23ccYgumGGGrw4D/ZmfF59/QDFfmHf15q8/dFKMT/FsfV2PH+B4qZl78g9W8bOSMbXU4OoehHEBOdV/KwzuqI0ksYnoyM5+hxnskaCvT6bZ7E2iFHmPkNBEXikqKcK/5g5CEdjiDt95XKFF02UL9tA7IXwMFtMOX1RoVJ9GCNxkJUSuzb/cZdvMnqlBrSAlD1hkQHOY+T6pyUwn3eQIzY3jaA380/Th/BkhutjhA9aHd2ZGSpvHMKgAz52gkL7d3MoGFW9Ir+azBk26c4DxNA0y32rdFtMnbtA/KdZKnz3ayCGMaQqEgCg4spYzkVE3eesBI18bcgSSzNLVj7RRAlKQWGJP9lXWc+C4KaZ8o4XUfCjBXV7nMwQH0kh6HCPu1WzmGNtcX1hllMZvHsj3OX11BS6utMCmI7f2KAB8dftN/GCqP6pe+ljGk="

r_github_packages:
  - sahirbhatnagar/manhattanly

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_github('sahirbhatnagar/manhattanly')"
  - Rscript -e "if (!require('devtools')) install.packages('plotly')"
  - Rscript -e "if (!require('devtools')) install.packages('ggplot2')"
  - Rscript -e "if (!require('devtools')) install.packages('magrittr')"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

cache:
  packages: yes

